# Generated by Django 4.2.3 on 2023-07-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turtlequery', '0002_auto_20230627_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turtlequery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
